### ISSUE TITLE
Is project abandoned?

### ISSUE THREAD

**Issue by 3oheicrw-ver2** [rodrigocfd/winlamb#20]
In favor of the new Rust based [winsafe](https://github.com/rodrigocfd/winsafe)?

**Comment by rodrigocfd** [comment]
Not abandoned, just feature complete.

WinSafe, in the other hand, is being actively developed because it has a much wider scope – it's not just a GUI wrapper, it's a safe wrapper over the **whole** Win32 API. Very ambitious project, and likely to never be finished, due to the sheer size of the Win32 API... but at some point in the future it will be large enough to be useful to most projects (I hope).
